### ISSUE TITLE
2018 Platform not available on prod homepage

### ISSUE THREAD

**Issue by chynnakeys** [cfpb/hmda-homepage#108]
The 2018 platform is not available to users on prod unless they use the URL https://ffiec.cfpb.gov/filing/2018/. Otherwise, they're redirected to the 2017 platform if they select the link on the homepage. 

They should be directed to the 2018 platform upon selecting the hmda platform link on the homepage

**Comment by omnipresent07** [comment]
This is also happening on the homepage at this link "Get started filing your HMDA data for 2019". This should instead be "Get started filing your HMDA data for 2018" and point to "/filing/2018/"
