### ISSUE TITLE
Make consent and PRA headings smaller

### ISSUE THREAD

**Issue by awolfe76** [cfpb/hmda-homepage#3]
Let's make these headings `<h4>`s instead of `<h3>`s.

Let's also set a `max-width` on the paragraph content here (`max-width: 77rem`).

I think we can also add a bit more spacing between the "CFPB Notice and Consent Banner" and the section (the 3 columns) above.

**Comment by Scotchester** [comment]
Accessibility Cop says don't just change the markup! Ensure that your HTML
heading elements stay in the correct hierarchy! 👮😁

**Comment by awolfe76** [comment]
Yeah, we're actually good in this case. It's a different section (and if taking the document as a whole, `<h4>` follows the hierarchy better here).

Thanks though. :)
